### ISSUE TITLE
Missing input for Ollama Text Describer node

### ISSUE THREAD

**Issue by eclaassens** [alisson-anjos/ComfyUI-Ollama-Describer#7]
Just installed you custom nodes via node manager. The image describer works like a charm but I wanted to test out your example workflow and that just doesn't work anymore. Added the Text Describers node and see I'm missing the input node. Also your node preview image https://github.com/alisson-anjos/ComfyUI-Ollama-Describer/blob/main/image-1.png is not showing the input unlike the workflow example image https://github.com/alisson-anjos/ComfyUI-Ollama-Describer/blob/main/image.png

Am I missing something?

**Comment by alisson-anjos** [comment]
Yes, the image is not consistent with the current situation of the nodes, I will try to update the image as soon as possible, as for the workflow I have already updated it, apart from that I have now also added 2 new nodes to make caption.
